### ISSUE TITLE
关于敏感词汇检查问题

### ISSUE THREAD

**Issue by Halleyth** [SetoKaiba/SourceDanmakuBugFeedback#1]
在注册邮箱的时候，我的邮箱名称中也被包含了敏感词汇，能否改进敏感词汇识别机制？

> email contains sensitive word: yth00,

**Comment by SetoKaiba** [comment]
目前的敏感词表用的是，工信部给到ICP那边的列表的，的确会比较严，所以我现在都是等反馈了后，我就去手动移除掉一些非政治敏感的敏感词。
因为这是一个涉及到网站域名的敏感词，我现在已移除。
